disabled_rules:
  - todo
  - trailing_comma

included:
  - Sources/
  - Tests/

excluded:
  - Fixtures/

identifier_name:
  excluded:
    - h1
    - h2
    - h3
    - p1
    - p2

type_name:
  excluded:
    - T

