---
version: 3.0.0
configurations:
  debug:
    A: 123
targets:
  watchOSTest:
    platform: ios
    type: ":application.watchapp2-container"
    references:
      - watchOSTestWatchApp
    configuration:
      PRODUCT_BUNDLE_IDENTIFIER: uk.lyptt.watchOSTest
      CURRENT_PROJECT_VERSION: "1"
      MARKETING_VERSION: "1.0"
  watchOSTestWatchApp:
    sources: watchOSTestWatchApp
    type: ":application.watchapp2"
    platform: watch
    references:
    - watchOSTestWatchExtension
    configuration:
      INFOPLIST_FILE: watchOSTestWatchApp/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: uk.lyptt.watchOSTest.watchOSTestWatchApp
      IBSC_MODULE: watchOSTestWatchExtension
  watchOSTestWatchExtension:
    sources: watchOSTestWatchExtension
    type: ":watchkit2-extension"
    platform: watch
    configuration:
      INFOPLIST_FILE: watchOSTestWatchExtension/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: uk.lyptt.watchOSTest.watchOSTestWatchApp.watchOSTestWatchExtension
