# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Swift Internals
email: swift-dev@lists.swift.org
description: > # > means to ignore newlines until the next unindented line
  Official guidelines for Swift API design.
timezone: America/Los_Angeles
baseurl: "/swift-internals"
url: "http://apple.github.io"

exclude: [config.ru, Gemfile, Gemfile.lock, Procfile, vendor, README.md]

# twitter_username: SwiftLang
# github_username:  jekyll

# Build settings
markdown: kramdown

kramdown:
    syntax_highlighter: rouge

sass:
    style: compressed
    sass_dir: _sass

gems:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      official_site: http://apple.github.io
      official_url: ""
      include_in_navigation: true
