
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// class java.lang.Character$UnicodeScript ///

public enum Character_UnicodeScript: Int, JNIObjectProtocol, JNIObjectInit {

    case COMMON, LATIN, GREEK, CYRILLIC, ARMENIAN, HEBREW, ARABIC, SYRIAC, THAANA, DEVANAGARI, BENGALI, GURMUKHI, GUJARATI, ORIYA, TAMIL, TELUGU, KANNADA, MALAYALAM, SINHALA, THAI, LAO, TIBETAN, MYANMAR, GEORGIAN, HANGUL, ETHIOPIC, CHEROKEE, CANADIAN_ABORIGINAL, OGHAM, RUNIC, KHMER, MONGOLIAN, HIRAGANA, KATAKANA, BOPOMOFO, HAN, YI, OLD_ITALIC, GOTHIC, DESERET, INHERITED, TAGALOG, HANUNOO, BUHID, TAGBANWA, LIMBU, TAI_LE, LINEAR_B, UGARITIC, SHAVIAN, OSMANYA, CYPRIOT, BRAILLE, BUGINESE, COPTIC, NEW_TAI_LUE, GLAGOLITIC, TIFINAGH, SYLOTI_NAGRI, OLD_PERSIAN, KHAROSHTHI, BALINESE, CUNEIFORM, PHOENICIAN, PHAGS_PA, NKO, SUNDANESE, BATAK, LEPCHA, OL_CHIKI, VAI, SAURASHTRA, KAYAH_LI, REJANG, LYCIAN, CARIAN, LYDIAN, CHAM, TAI_THAM, TAI_VIET, AVESTAN, EGYPTIAN_HIEROGLYPHS, SAMARITAN, MANDAIC, LISU, BAMUM, JAVANESE, MEETEI_MAYEK, IMPERIAL_ARAMAIC, OLD_SOUTH_ARABIAN, INSCRIPTIONAL_PARTHIAN, INSCRIPTIONAL_PAHLAVI, OLD_TURKIC, BRAHMI, KAITHI, MEROITIC_HIEROGLYPHS, MEROITIC_CURSIVE, SORA_SOMPENG, CHAKMA, SHARADA, TAKRI, MIAO, UNKNOWN

    static let enumConstants = JavaClass(loading: "java.lang.Character$UnicodeScript")
        .getEnumConstants()!.map { Character_UnicodeScriptForward( javaObject: $0.javaObject ) }

    public func underlier() -> Character_UnicodeScriptForward {
        return Character_UnicodeScript.enumConstants[self.rawValue]
    }

    public func localJavaObject(_ locals: UnsafeMutablePointer<[jobject]>) -> jobject? {
        return underlier().localJavaObject( locals )
    }

    public init( javaObject: jobject? ) {
        self = Character_UnicodeScript( rawValue: JavaEnum( javaObject: javaObject ).ordinal() )!
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.forName(java.lang.String)

    private static var forName_MethodID_1: jmethodID?

    public static func forName( scriptName: String? ) -> Character_UnicodeScript! {
        return Character_UnicodeScriptForward.forName( scriptName: scriptName )
    }
    public static func forName( _ _scriptName: String? ) -> Character_UnicodeScript! {
        return forName( scriptName: _scriptName )
    }

    /// public static java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.of(int)

    private static var of_MethodID_2: jmethodID?

    public static func of( codePoint: Int ) -> Character_UnicodeScript! {
        return Character_UnicodeScriptForward.of( codePoint: codePoint )
    }
    public static func of( _ _codePoint: Int ) -> Character_UnicodeScript! {
        return of( codePoint: _codePoint )
    }

    /// public static java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.valueOf(java.lang.String)

    private static var valueOf_MethodID_3: jmethodID?

    public static func valueOf( name: String? ) -> Character_UnicodeScript! {
        return Character_UnicodeScriptForward.valueOf( name: name )
    }
    public static func valueOf( _ _name: String? ) -> Character_UnicodeScript! {
        return valueOf( name: _name )
    }

    /// public static java.lang.Character$UnicodeScript[] java.lang.Character$UnicodeScript.values()

    private static var values_MethodID_4: jmethodID?

    public static func values() -> [Character_UnicodeScript]! {
        return Character_UnicodeScriptForward.values( )
    }

}


open class Character_UnicodeScriptForward: JNIObjectForward {

    private static var Character_UnicodeScriptJNIClass: jclass?

    /// private static final java.lang.Character$UnicodeScript[] java.lang.Character$UnicodeScript.$VALUES

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.ARABIC

    private static var ARABIC_FieldID: jfieldID?

    public static var ARABIC: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "ARABIC", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &ARABIC_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.ARMENIAN

    private static var ARMENIAN_FieldID: jfieldID?

    public static var ARMENIAN: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "ARMENIAN", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &ARMENIAN_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.AVESTAN

    private static var AVESTAN_FieldID: jfieldID?

    public static var AVESTAN: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "AVESTAN", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &AVESTAN_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.BALINESE

    private static var BALINESE_FieldID: jfieldID?

    public static var BALINESE: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "BALINESE", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &BALINESE_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.BAMUM

    private static var BAMUM_FieldID: jfieldID?

    public static var BAMUM: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "BAMUM", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &BAMUM_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.BATAK

    private static var BATAK_FieldID: jfieldID?

    public static var BATAK: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "BATAK", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &BATAK_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.BENGALI

    private static var BENGALI_FieldID: jfieldID?

    public static var BENGALI: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "BENGALI", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &BENGALI_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.BOPOMOFO

    private static var BOPOMOFO_FieldID: jfieldID?

    public static var BOPOMOFO: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "BOPOMOFO", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &BOPOMOFO_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.BRAHMI

    private static var BRAHMI_FieldID: jfieldID?

    public static var BRAHMI: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "BRAHMI", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &BRAHMI_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.BRAILLE

    private static var BRAILLE_FieldID: jfieldID?

    public static var BRAILLE: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "BRAILLE", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &BRAILLE_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.BUGINESE

    private static var BUGINESE_FieldID: jfieldID?

    public static var BUGINESE: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "BUGINESE", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &BUGINESE_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.BUHID

    private static var BUHID_FieldID: jfieldID?

    public static var BUHID: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "BUHID", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &BUHID_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.CANADIAN_ABORIGINAL

    private static var CANADIAN_ABORIGINAL_FieldID: jfieldID?

    public static var CANADIAN_ABORIGINAL: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "CANADIAN_ABORIGINAL", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &CANADIAN_ABORIGINAL_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.CARIAN

    private static var CARIAN_FieldID: jfieldID?

    public static var CARIAN: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "CARIAN", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &CARIAN_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.CHAKMA

    private static var CHAKMA_FieldID: jfieldID?

    public static var CHAKMA: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "CHAKMA", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &CHAKMA_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.CHAM

    private static var CHAM_FieldID: jfieldID?

    public static var CHAM: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "CHAM", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &CHAM_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.CHEROKEE

    private static var CHEROKEE_FieldID: jfieldID?

    public static var CHEROKEE: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "CHEROKEE", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &CHEROKEE_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.COMMON

    private static var COMMON_FieldID: jfieldID?

    public static var COMMON: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "COMMON", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &COMMON_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.COPTIC

    private static var COPTIC_FieldID: jfieldID?

    public static var COPTIC: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "COPTIC", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &COPTIC_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.CUNEIFORM

    private static var CUNEIFORM_FieldID: jfieldID?

    public static var CUNEIFORM: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "CUNEIFORM", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &CUNEIFORM_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.CYPRIOT

    private static var CYPRIOT_FieldID: jfieldID?

    public static var CYPRIOT: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "CYPRIOT", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &CYPRIOT_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.CYRILLIC

    private static var CYRILLIC_FieldID: jfieldID?

    public static var CYRILLIC: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "CYRILLIC", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &CYRILLIC_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.DESERET

    private static var DESERET_FieldID: jfieldID?

    public static var DESERET: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "DESERET", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &DESERET_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.DEVANAGARI

    private static var DEVANAGARI_FieldID: jfieldID?

    public static var DEVANAGARI: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "DEVANAGARI", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &DEVANAGARI_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.EGYPTIAN_HIEROGLYPHS

    private static var EGYPTIAN_HIEROGLYPHS_FieldID: jfieldID?

    public static var EGYPTIAN_HIEROGLYPHS: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "EGYPTIAN_HIEROGLYPHS", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &EGYPTIAN_HIEROGLYPHS_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.ETHIOPIC

    private static var ETHIOPIC_FieldID: jfieldID?

    public static var ETHIOPIC: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "ETHIOPIC", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &ETHIOPIC_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.GEORGIAN

    private static var GEORGIAN_FieldID: jfieldID?

    public static var GEORGIAN: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "GEORGIAN", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &GEORGIAN_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.GLAGOLITIC

    private static var GLAGOLITIC_FieldID: jfieldID?

    public static var GLAGOLITIC: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "GLAGOLITIC", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &GLAGOLITIC_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.GOTHIC

    private static var GOTHIC_FieldID: jfieldID?

    public static var GOTHIC: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "GOTHIC", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &GOTHIC_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.GREEK

    private static var GREEK_FieldID: jfieldID?

    public static var GREEK: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "GREEK", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &GREEK_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.GUJARATI

    private static var GUJARATI_FieldID: jfieldID?

    public static var GUJARATI: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "GUJARATI", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &GUJARATI_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.GURMUKHI

    private static var GURMUKHI_FieldID: jfieldID?

    public static var GURMUKHI: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "GURMUKHI", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &GURMUKHI_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.HAN

    private static var HAN_FieldID: jfieldID?

    public static var HAN: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "HAN", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &HAN_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.HANGUL

    private static var HANGUL_FieldID: jfieldID?

    public static var HANGUL: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "HANGUL", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &HANGUL_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.HANUNOO

    private static var HANUNOO_FieldID: jfieldID?

    public static var HANUNOO: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "HANUNOO", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &HANUNOO_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.HEBREW

    private static var HEBREW_FieldID: jfieldID?

    public static var HEBREW: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "HEBREW", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &HEBREW_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.HIRAGANA

    private static var HIRAGANA_FieldID: jfieldID?

    public static var HIRAGANA: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "HIRAGANA", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &HIRAGANA_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.IMPERIAL_ARAMAIC

    private static var IMPERIAL_ARAMAIC_FieldID: jfieldID?

    public static var IMPERIAL_ARAMAIC: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "IMPERIAL_ARAMAIC", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &IMPERIAL_ARAMAIC_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.INHERITED

    private static var INHERITED_FieldID: jfieldID?

    public static var INHERITED: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "INHERITED", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &INHERITED_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.INSCRIPTIONAL_PAHLAVI

    private static var INSCRIPTIONAL_PAHLAVI_FieldID: jfieldID?

    public static var INSCRIPTIONAL_PAHLAVI: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "INSCRIPTIONAL_PAHLAVI", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &INSCRIPTIONAL_PAHLAVI_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.INSCRIPTIONAL_PARTHIAN

    private static var INSCRIPTIONAL_PARTHIAN_FieldID: jfieldID?

    public static var INSCRIPTIONAL_PARTHIAN: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "INSCRIPTIONAL_PARTHIAN", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &INSCRIPTIONAL_PARTHIAN_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.JAVANESE

    private static var JAVANESE_FieldID: jfieldID?

    public static var JAVANESE: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "JAVANESE", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &JAVANESE_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.KAITHI

    private static var KAITHI_FieldID: jfieldID?

    public static var KAITHI: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "KAITHI", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &KAITHI_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.KANNADA

    private static var KANNADA_FieldID: jfieldID?

    public static var KANNADA: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "KANNADA", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &KANNADA_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.KATAKANA

    private static var KATAKANA_FieldID: jfieldID?

    public static var KATAKANA: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "KATAKANA", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &KATAKANA_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.KAYAH_LI

    private static var KAYAH_LI_FieldID: jfieldID?

    public static var KAYAH_LI: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "KAYAH_LI", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &KAYAH_LI_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.KHAROSHTHI

    private static var KHAROSHTHI_FieldID: jfieldID?

    public static var KHAROSHTHI: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "KHAROSHTHI", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &KHAROSHTHI_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.KHMER

    private static var KHMER_FieldID: jfieldID?

    public static var KHMER: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "KHMER", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &KHMER_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.LAO

    private static var LAO_FieldID: jfieldID?

    public static var LAO: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "LAO", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &LAO_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.LATIN

    private static var LATIN_FieldID: jfieldID?

    public static var LATIN: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "LATIN", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &LATIN_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.LEPCHA

    private static var LEPCHA_FieldID: jfieldID?

    public static var LEPCHA: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "LEPCHA", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &LEPCHA_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.LIMBU

    private static var LIMBU_FieldID: jfieldID?

    public static var LIMBU: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "LIMBU", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &LIMBU_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.LINEAR_B

    private static var LINEAR_B_FieldID: jfieldID?

    public static var LINEAR_B: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "LINEAR_B", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &LINEAR_B_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.LISU

    private static var LISU_FieldID: jfieldID?

    public static var LISU: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "LISU", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &LISU_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.LYCIAN

    private static var LYCIAN_FieldID: jfieldID?

    public static var LYCIAN: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "LYCIAN", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &LYCIAN_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.LYDIAN

    private static var LYDIAN_FieldID: jfieldID?

    public static var LYDIAN: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "LYDIAN", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &LYDIAN_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.MALAYALAM

    private static var MALAYALAM_FieldID: jfieldID?

    public static var MALAYALAM: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "MALAYALAM", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &MALAYALAM_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.MANDAIC

    private static var MANDAIC_FieldID: jfieldID?

    public static var MANDAIC: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "MANDAIC", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &MANDAIC_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.MEETEI_MAYEK

    private static var MEETEI_MAYEK_FieldID: jfieldID?

    public static var MEETEI_MAYEK: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "MEETEI_MAYEK", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &MEETEI_MAYEK_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.MEROITIC_CURSIVE

    private static var MEROITIC_CURSIVE_FieldID: jfieldID?

    public static var MEROITIC_CURSIVE: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "MEROITIC_CURSIVE", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &MEROITIC_CURSIVE_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.MEROITIC_HIEROGLYPHS

    private static var MEROITIC_HIEROGLYPHS_FieldID: jfieldID?

    public static var MEROITIC_HIEROGLYPHS: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "MEROITIC_HIEROGLYPHS", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &MEROITIC_HIEROGLYPHS_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.MIAO

    private static var MIAO_FieldID: jfieldID?

    public static var MIAO: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "MIAO", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &MIAO_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.MONGOLIAN

    private static var MONGOLIAN_FieldID: jfieldID?

    public static var MONGOLIAN: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "MONGOLIAN", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &MONGOLIAN_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.MYANMAR

    private static var MYANMAR_FieldID: jfieldID?

    public static var MYANMAR: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "MYANMAR", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &MYANMAR_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.NEW_TAI_LUE

    private static var NEW_TAI_LUE_FieldID: jfieldID?

    public static var NEW_TAI_LUE: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "NEW_TAI_LUE", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &NEW_TAI_LUE_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.NKO

    private static var NKO_FieldID: jfieldID?

    public static var NKO: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "NKO", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &NKO_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.OGHAM

    private static var OGHAM_FieldID: jfieldID?

    public static var OGHAM: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "OGHAM", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &OGHAM_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.OLD_ITALIC

    private static var OLD_ITALIC_FieldID: jfieldID?

    public static var OLD_ITALIC: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "OLD_ITALIC", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &OLD_ITALIC_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.OLD_PERSIAN

    private static var OLD_PERSIAN_FieldID: jfieldID?

    public static var OLD_PERSIAN: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "OLD_PERSIAN", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &OLD_PERSIAN_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.OLD_SOUTH_ARABIAN

    private static var OLD_SOUTH_ARABIAN_FieldID: jfieldID?

    public static var OLD_SOUTH_ARABIAN: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "OLD_SOUTH_ARABIAN", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &OLD_SOUTH_ARABIAN_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.OLD_TURKIC

    private static var OLD_TURKIC_FieldID: jfieldID?

    public static var OLD_TURKIC: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "OLD_TURKIC", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &OLD_TURKIC_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.OL_CHIKI

    private static var OL_CHIKI_FieldID: jfieldID?

    public static var OL_CHIKI: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "OL_CHIKI", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &OL_CHIKI_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.ORIYA

    private static var ORIYA_FieldID: jfieldID?

    public static var ORIYA: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "ORIYA", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &ORIYA_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.OSMANYA

    private static var OSMANYA_FieldID: jfieldID?

    public static var OSMANYA: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "OSMANYA", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &OSMANYA_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.PHAGS_PA

    private static var PHAGS_PA_FieldID: jfieldID?

    public static var PHAGS_PA: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "PHAGS_PA", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &PHAGS_PA_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.PHOENICIAN

    private static var PHOENICIAN_FieldID: jfieldID?

    public static var PHOENICIAN: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "PHOENICIAN", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &PHOENICIAN_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.REJANG

    private static var REJANG_FieldID: jfieldID?

    public static var REJANG: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "REJANG", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &REJANG_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.RUNIC

    private static var RUNIC_FieldID: jfieldID?

    public static var RUNIC: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "RUNIC", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &RUNIC_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.SAMARITAN

    private static var SAMARITAN_FieldID: jfieldID?

    public static var SAMARITAN: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "SAMARITAN", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &SAMARITAN_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.SAURASHTRA

    private static var SAURASHTRA_FieldID: jfieldID?

    public static var SAURASHTRA: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "SAURASHTRA", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &SAURASHTRA_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.SHARADA

    private static var SHARADA_FieldID: jfieldID?

    public static var SHARADA: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "SHARADA", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &SHARADA_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.SHAVIAN

    private static var SHAVIAN_FieldID: jfieldID?

    public static var SHAVIAN: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "SHAVIAN", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &SHAVIAN_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.SINHALA

    private static var SINHALA_FieldID: jfieldID?

    public static var SINHALA: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "SINHALA", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &SINHALA_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.SORA_SOMPENG

    private static var SORA_SOMPENG_FieldID: jfieldID?

    public static var SORA_SOMPENG: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "SORA_SOMPENG", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &SORA_SOMPENG_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.SUNDANESE

    private static var SUNDANESE_FieldID: jfieldID?

    public static var SUNDANESE: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "SUNDANESE", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &SUNDANESE_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.SYLOTI_NAGRI

    private static var SYLOTI_NAGRI_FieldID: jfieldID?

    public static var SYLOTI_NAGRI: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "SYLOTI_NAGRI", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &SYLOTI_NAGRI_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.SYRIAC

    private static var SYRIAC_FieldID: jfieldID?

    public static var SYRIAC: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "SYRIAC", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &SYRIAC_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.TAGALOG

    private static var TAGALOG_FieldID: jfieldID?

    public static var TAGALOG: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "TAGALOG", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &TAGALOG_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.TAGBANWA

    private static var TAGBANWA_FieldID: jfieldID?

    public static var TAGBANWA: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "TAGBANWA", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &TAGBANWA_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.TAI_LE

    private static var TAI_LE_FieldID: jfieldID?

    public static var TAI_LE: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "TAI_LE", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &TAI_LE_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.TAI_THAM

    private static var TAI_THAM_FieldID: jfieldID?

    public static var TAI_THAM: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "TAI_THAM", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &TAI_THAM_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.TAI_VIET

    private static var TAI_VIET_FieldID: jfieldID?

    public static var TAI_VIET: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "TAI_VIET", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &TAI_VIET_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.TAKRI

    private static var TAKRI_FieldID: jfieldID?

    public static var TAKRI: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "TAKRI", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &TAKRI_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.TAMIL

    private static var TAMIL_FieldID: jfieldID?

    public static var TAMIL: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "TAMIL", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &TAMIL_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.TELUGU

    private static var TELUGU_FieldID: jfieldID?

    public static var TELUGU: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "TELUGU", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &TELUGU_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.THAANA

    private static var THAANA_FieldID: jfieldID?

    public static var THAANA: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "THAANA", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &THAANA_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.THAI

    private static var THAI_FieldID: jfieldID?

    public static var THAI: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "THAI", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &THAI_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.TIBETAN

    private static var TIBETAN_FieldID: jfieldID?

    public static var TIBETAN: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "TIBETAN", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &TIBETAN_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.TIFINAGH

    private static var TIFINAGH_FieldID: jfieldID?

    public static var TIFINAGH: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "TIFINAGH", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &TIFINAGH_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.UGARITIC

    private static var UGARITIC_FieldID: jfieldID?

    public static var UGARITIC: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "UGARITIC", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &UGARITIC_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.UNKNOWN

    private static var UNKNOWN_FieldID: jfieldID?

    public static var UNKNOWN: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "UNKNOWN", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &UNKNOWN_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.VAI

    private static var VAI_FieldID: jfieldID?

    public static var VAI: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "VAI", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &VAI_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.YI

    private static var YI_FieldID: jfieldID?

    public static var YI: Character_UnicodeScript! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "YI", fieldType: "Ljava/lang/Character$UnicodeScript;", fieldCache: &YI_FieldID, className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? Character_UnicodeScript( javaObject: __value ) : nil
        }
    }

    /// private static java.util.HashMap java.lang.Character$UnicodeScript.aliases

    /// private static final int[] java.lang.Character$UnicodeScript.scriptStarts

    /// private static final java.lang.Character$UnicodeScript[] java.lang.Character$UnicodeScript.scripts

    /// public static final java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.forName(java.lang.String)

    private static var forName_MethodID_5: jmethodID?

    open class func forName( scriptName: String? ) -> Character_UnicodeScript! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: scriptName, locals: &__locals )
        let __return = JNIMethod.CallStaticObjectMethod( className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass, methodName: "forName", methodSig: "(Ljava/lang/String;)Ljava/lang/Character$UnicodeScript;", methodCache: &forName_MethodID_5, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? Character_UnicodeScript( javaObject: __return ) : nil
    }

    open class func forName( _ _scriptName: String? ) -> Character_UnicodeScript! {
        return forName( scriptName: _scriptName )
    }

    /// public static java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.of(int)

    private static var of_MethodID_6: jmethodID?

    open class func of( codePoint: Int ) -> Character_UnicodeScript! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = jvalue( i: jint(codePoint) )
        let __return = JNIMethod.CallStaticObjectMethod( className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass, methodName: "of", methodSig: "(I)Ljava/lang/Character$UnicodeScript;", methodCache: &of_MethodID_6, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? Character_UnicodeScript( javaObject: __return ) : nil
    }

    open class func of( _ _codePoint: Int ) -> Character_UnicodeScript! {
        return of( codePoint: _codePoint )
    }

    /// public static java.lang.Character$UnicodeScript java.lang.Character$UnicodeScript.valueOf(java.lang.String)

    private static var valueOf_MethodID_7: jmethodID?

    open class func valueOf( name: String? ) -> Character_UnicodeScript! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: name, locals: &__locals )
        let __return = JNIMethod.CallStaticObjectMethod( className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass, methodName: "valueOf", methodSig: "(Ljava/lang/String;)Ljava/lang/Character$UnicodeScript;", methodCache: &valueOf_MethodID_7, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? Character_UnicodeScript( javaObject: __return ) : nil
    }

    open class func valueOf( _ _name: String? ) -> Character_UnicodeScript! {
        return valueOf( name: _name )
    }

    /// public static java.lang.Enum java.lang.Enum.valueOf(java.lang.Class,java.lang.String)

    private static var valueOf_MethodID_8: jmethodID?

    open class func valueOf( enumType: java_swift.JavaClass?, name: String? ) -> java_swift.JavaEnum! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 2 )
        __args[0] = JNIType.toJava( value: enumType, locals: &__locals )
        __args[1] = JNIType.toJava( value: name, locals: &__locals )
        let __return = JNIMethod.CallStaticObjectMethod( className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass, methodName: "valueOf", methodSig: "(Ljava/lang/Class;Ljava/lang/String;)Ljava/lang/Enum;", methodCache: &valueOf_MethodID_8, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? java_swift.JavaEnum( javaObject: __return ) : nil
    }

    open class func valueOf( _ _enumType: java_swift.JavaClass?, _ _name: String? ) -> java_swift.JavaEnum! {
        return valueOf( enumType: _enumType, name: _name )
    }

    /// public static java.lang.Character$UnicodeScript[] java.lang.Character$UnicodeScript.values()

    private static var values_MethodID_9: jmethodID?

    open class func values() -> [Character_UnicodeScript]! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallStaticObjectMethod( className: "java/lang/Character$UnicodeScript", classCache: &Character_UnicodeScriptJNIClass, methodName: "values", methodSig: "()[Ljava/lang/Character$UnicodeScript;", methodCache: &values_MethodID_9, args: &__args, locals: &__locals )
        return JNIType.toSwift( type: [Character_UnicodeScript].self, from: __return )
    }


    /// public final int java.lang.Enum.compareTo(java.lang.Enum)

    // Skipping method: false true false false false 

    /// public int java.lang.Enum.compareTo(java.lang.Object)

    // Skipping method: false true false false false 

    /// public final boolean java.lang.Enum.equals(java.lang.Object)

    // Skipping method: false true false false false 

    /// public final native java.lang.Class java.lang.Object.getClass()

    // Skipping method: false true false false false 

    /// public final java.lang.Class java.lang.Enum.getDeclaringClass()

    // Skipping method: false true false false false 

    /// public final int java.lang.Enum.hashCode()

    // Skipping method: false true false false false 

    /// public final java.lang.String java.lang.Enum.name()

    // Skipping method: false true false false false 

    /// public final native void java.lang.Object.notify()

    // Skipping method: false true false false false 

    /// public final native void java.lang.Object.notifyAll()

    // Skipping method: false true false false false 

    /// public final int java.lang.Enum.ordinal()

    // Skipping method: false true false false false 

    /// public java.lang.String java.lang.Enum.toString()

    // Skipping method: false true false false false 

    /// public final native void java.lang.Object.wait(long) throws java.lang.InterruptedException

    // Skipping method: false true false false false 

    /// public final void java.lang.Object.wait(long,int) throws java.lang.InterruptedException

    // Skipping method: false true false false false 

    /// public final void java.lang.Object.wait() throws java.lang.InterruptedException

    // Skipping method: false true false false false 

}

