
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// interface java.lang.CharSequence ///

public protocol CharSequence: JavaProtocol {

    /// public abstract char java.lang.CharSequence.charAt(int)

    func charAt( arg0: Int ) -> UInt16

    /// public default java.util.stream.IntStream java.lang.CharSequence.chars()

    // Skipping method: false false true false false 

    /// public default java.util.stream.IntStream java.lang.CharSequence.codePoints()

    // Skipping method: false false true false false 

    /// private java.util.Spliterator$OfInt java.lang.CharSequence.lambda$chars$0()

    /// private java.util.Spliterator$OfInt java.lang.CharSequence.lambda$codePoints$1()

    /// public abstract int java.lang.CharSequence.length()

    func length() -> Int

    /// public abstract java.lang.CharSequence java.lang.CharSequence.subSequence(int,int)

    func subSequence( arg0: Int, arg1: Int ) -> CharSequence!

    /// public abstract java.lang.String java.lang.CharSequence.toString()

    func toString() -> String!

}


open class CharSequenceForward: JNIObjectForward, CharSequence {

    private static var CharSequenceJNIClass: jclass?

    /// public abstract char java.lang.CharSequence.charAt(int)

    private static var charAt_MethodID_5: jmethodID?

    open func charAt( arg0: Int ) -> UInt16 {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = jvalue( i: jint(arg0) )
        let __return = JNIMethod.CallCharMethod( object: javaObject, methodName: "charAt", methodSig: "(I)C", methodCache: &CharSequenceForward.charAt_MethodID_5, args: &__args, locals: &__locals )
        return __return
    }

    open func charAt( _ _arg0: Int ) -> UInt16 {
        return charAt( arg0: _arg0 )
    }

    /// public default java.util.stream.IntStream java.lang.CharSequence.chars()

    // Skipping method: false false true false false 

    /// public default java.util.stream.IntStream java.lang.CharSequence.codePoints()

    // Skipping method: false false true false false 

    /// public abstract int java.lang.CharSequence.length()

    private static var length_MethodID_6: jmethodID?

    open func length() -> Int {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallIntMethod( object: javaObject, methodName: "length", methodSig: "()I", methodCache: &CharSequenceForward.length_MethodID_6, args: &__args, locals: &__locals )
        return Int(__return)
    }


    /// public abstract java.lang.CharSequence java.lang.CharSequence.subSequence(int,int)

    private static var subSequence_MethodID_7: jmethodID?

    open func subSequence( arg0: Int, arg1: Int ) -> CharSequence! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 2 )
        __args[0] = jvalue( i: jint(arg0) )
        __args[1] = jvalue( i: jint(arg1) )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "subSequence", methodSig: "(II)Ljava/lang/CharSequence;", methodCache: &CharSequenceForward.subSequence_MethodID_7, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? CharSequenceForward( javaObject: __return ) : nil
    }

    open func subSequence( _ _arg0: Int, _ _arg1: Int ) -> CharSequence! {
        return subSequence( arg0: _arg0, arg1: _arg1 )
    }

    /// public abstract java.lang.String java.lang.CharSequence.toString()

    private static var toString_MethodID_8: jmethodID?

    open func toString() -> String! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "toString", methodSig: "()Ljava/lang/String;", methodCache: &CharSequenceForward.toString_MethodID_8, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? String( javaObject: __return ) : nil
    }


}

