
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// interface java.lang.management.ClassLoadingMXBean ///

public protocol ClassLoadingMXBean: PlatformManagedObject {

    /// public abstract int java.lang.management.ClassLoadingMXBean.getLoadedClassCount()

    func getLoadedClassCount() -> Int

    /// public abstract long java.lang.management.ClassLoadingMXBean.getTotalLoadedClassCount()

    func getTotalLoadedClassCount() -> Int64

    /// public abstract long java.lang.management.ClassLoadingMXBean.getUnloadedClassCount()

    func getUnloadedClassCount() -> Int64

    /// public abstract boolean java.lang.management.ClassLoadingMXBean.isVerbose()

    func isVerbose() -> Bool

    /// public abstract void java.lang.management.ClassLoadingMXBean.setVerbose(boolean)

    func setVerbose( value: Bool )

}


open class ClassLoadingMXBeanForward: PlatformManagedObjectForward, ClassLoadingMXBean {

    private static var ClassLoadingMXBeanJNIClass: jclass?

    /// public abstract int java.lang.management.ClassLoadingMXBean.getLoadedClassCount()

    private static var getLoadedClassCount_MethodID_6: jmethodID?

    open func getLoadedClassCount() -> Int {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallIntMethod( object: javaObject, methodName: "getLoadedClassCount", methodSig: "()I", methodCache: &ClassLoadingMXBeanForward.getLoadedClassCount_MethodID_6, args: &__args, locals: &__locals )
        return Int(__return)
    }


    /// public abstract javax.management.ObjectName java.lang.management.PlatformManagedObject.getObjectName()

    // Skipping method: false false true false false 

    /// public abstract long java.lang.management.ClassLoadingMXBean.getTotalLoadedClassCount()

    private static var getTotalLoadedClassCount_MethodID_7: jmethodID?

    open func getTotalLoadedClassCount() -> Int64 {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallLongMethod( object: javaObject, methodName: "getTotalLoadedClassCount", methodSig: "()J", methodCache: &ClassLoadingMXBeanForward.getTotalLoadedClassCount_MethodID_7, args: &__args, locals: &__locals )
        return __return
    }


    /// public abstract long java.lang.management.ClassLoadingMXBean.getUnloadedClassCount()

    private static var getUnloadedClassCount_MethodID_8: jmethodID?

    open func getUnloadedClassCount() -> Int64 {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallLongMethod( object: javaObject, methodName: "getUnloadedClassCount", methodSig: "()J", methodCache: &ClassLoadingMXBeanForward.getUnloadedClassCount_MethodID_8, args: &__args, locals: &__locals )
        return __return
    }


    /// public abstract boolean java.lang.management.ClassLoadingMXBean.isVerbose()

    private static var isVerbose_MethodID_9: jmethodID?

    open func isVerbose() -> Bool {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallBooleanMethod( object: javaObject, methodName: "isVerbose", methodSig: "()Z", methodCache: &ClassLoadingMXBeanForward.isVerbose_MethodID_9, args: &__args, locals: &__locals )
        return __return != jboolean(JNI_FALSE)
    }


    /// public abstract void java.lang.management.ClassLoadingMXBean.setVerbose(boolean)

    private static var setVerbose_MethodID_10: jmethodID?

    open func setVerbose( value: Bool ) {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = jvalue( z: jboolean(value ? JNI_TRUE : JNI_FALSE) )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "setVerbose", methodSig: "(Z)V", methodCache: &ClassLoadingMXBeanForward.setVerbose_MethodID_10, args: &__args, locals: &__locals )
    }

    open func setVerbose( _ _value: Bool ) {
        setVerbose( value: _value )
    }

    /// In declared protocol but not defined.. ///

    /// public abstract javax.management.ObjectName java.lang.management.PlatformManagedObject.getObjectName()

    // Skipping method: false false true false false 

}

