
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// class java.lang.ExceptionInInitializerError ///

open class ExceptionInInitializerError: LinkageError {

    public convenience init?( casting object: java_swift.JavaObject, _ file: StaticString = #file, _ line: Int = #line ) {
        self.init( javaObject: nil )
        object.withJavaObject {
            self.javaObject = $0
        }
    }

    private static var ExceptionInInitializerErrorJNIClass: jclass?

    /// private static final long java.lang.ExceptionInInitializerError.serialVersionUID

    /// private java.lang.Throwable java.lang.ExceptionInInitializerError.exception

    /// private static final long java.lang.LinkageError.serialVersionUID

    /// static final long java.lang.Error.serialVersionUID

    // Skipping field: true true false false false false 

    /// static final boolean java.lang.Throwable.$assertionsDisabled

    // Skipping field: true false false false false false 

    /// private static final java.lang.String java.lang.Throwable.CAUSE_CAPTION

    /// private static final java.lang.Throwable[] java.lang.Throwable.EMPTY_THROWABLE_ARRAY

    /// private static final java.lang.String java.lang.Throwable.NULL_CAUSE_MESSAGE

    /// private static final java.lang.String java.lang.Throwable.SELF_SUPPRESSION_MESSAGE

    /// private static final java.lang.String java.lang.Throwable.SUPPRESSED_CAPTION

    /// private static final java.util.List java.lang.Throwable.SUPPRESSED_SENTINEL

    /// private static final java.lang.StackTraceElement[] java.lang.Throwable.UNASSIGNED_STACK

    /// private static final long java.lang.Throwable.serialVersionUID

    /// private java.lang.Throwable java.lang.Throwable.cause

    /// private java.lang.String java.lang.Throwable.detailMessage

    /// private java.lang.StackTraceElement[] java.lang.Throwable.stackTrace

    /// private java.util.List java.lang.Throwable.suppressedExceptions

    /// public java.lang.ExceptionInInitializerError()

    private static var new_MethodID_1: jmethodID?

    public convenience init() {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __object = JNIMethod.NewObject( className: "java/lang/ExceptionInInitializerError", classCache: &ExceptionInInitializerError.ExceptionInInitializerErrorJNIClass, methodSig: "()V", methodCache: &ExceptionInInitializerError.new_MethodID_1, args: &__args, locals: &__locals )
        self.init( javaObject: __object )
        JNI.DeleteLocalRef( __object )
    }

    /// public java.lang.ExceptionInInitializerError(java.lang.String)

    private static var new_MethodID_2: jmethodID?

    public convenience init( s: String? ) {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: s, locals: &__locals )
        let __object = JNIMethod.NewObject( className: "java/lang/ExceptionInInitializerError", classCache: &ExceptionInInitializerError.ExceptionInInitializerErrorJNIClass, methodSig: "(Ljava/lang/String;)V", methodCache: &ExceptionInInitializerError.new_MethodID_2, args: &__args, locals: &__locals )
        self.init( javaObject: __object )
        JNI.DeleteLocalRef( __object )
    }

    public convenience init( _ _s: String? ) {
        self.init( s: _s )
    }

    /// public java.lang.ExceptionInInitializerError(java.lang.Throwable)

    private static var new_MethodID_3: jmethodID?

    public convenience init( thrown: java_swift.Throwable? ) {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: thrown, locals: &__locals )
        let __object = JNIMethod.NewObject( className: "java/lang/ExceptionInInitializerError", classCache: &ExceptionInInitializerError.ExceptionInInitializerErrorJNIClass, methodSig: "(Ljava/lang/Throwable;)V", methodCache: &ExceptionInInitializerError.new_MethodID_3, args: &__args, locals: &__locals )
        self.init( javaObject: __object )
        JNI.DeleteLocalRef( __object )
    }

    public convenience init( _ _thrown: java_swift.Throwable? ) {
        self.init( thrown: _thrown )
    }

    /// public java.lang.Throwable java.lang.ExceptionInInitializerError.getCause()

    // Skipping method: false true false false false 

    /// public java.lang.Throwable java.lang.ExceptionInInitializerError.getException()

    private static var getException_MethodID_4: jmethodID?

    open func getException() -> java_swift.Throwable! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "getException", methodSig: "()Ljava/lang/Throwable;", methodCache: &ExceptionInInitializerError.getException_MethodID_4, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? java_swift.Throwable( javaObject: __return ) : nil
    }


}

