
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// interface java.lang.annotation.Inherited ///

public protocol Inherited: Annotation {

}


open class InheritedForward: AnnotationForward, Inherited {

    private static var InheritedJNIClass: jclass?

}

