
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// interface java.lang.management.MemoryManagerMXBean ///

public protocol MemoryManagerMXBean: PlatformManagedObject {

    /// public abstract java.lang.String[] java.lang.management.MemoryManagerMXBean.getMemoryPoolNames()

    func getMemoryPoolNames() -> [String]!

    /// public abstract java.lang.String java.lang.management.MemoryManagerMXBean.getName()

    func getName() -> String!

    /// public abstract boolean java.lang.management.MemoryManagerMXBean.isValid()

    func isValid() -> Bool

}


open class MemoryManagerMXBeanForward: PlatformManagedObjectForward, MemoryManagerMXBean {

    private static var MemoryManagerMXBeanJNIClass: jclass?

    /// public abstract java.lang.String[] java.lang.management.MemoryManagerMXBean.getMemoryPoolNames()

    private static var getMemoryPoolNames_MethodID_4: jmethodID?

    open func getMemoryPoolNames() -> [String]! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "getMemoryPoolNames", methodSig: "()[Ljava/lang/String;", methodCache: &MemoryManagerMXBeanForward.getMemoryPoolNames_MethodID_4, args: &__args, locals: &__locals )
        return JNIType.toSwift( type: [String].self, from: __return )
    }


    /// public abstract java.lang.String java.lang.management.MemoryManagerMXBean.getName()

    private static var getName_MethodID_5: jmethodID?

    open func getName() -> String! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "getName", methodSig: "()Ljava/lang/String;", methodCache: &MemoryManagerMXBeanForward.getName_MethodID_5, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? String( javaObject: __return ) : nil
    }


    /// public abstract javax.management.ObjectName java.lang.management.PlatformManagedObject.getObjectName()

    // Skipping method: false false true false false 

    /// public abstract boolean java.lang.management.MemoryManagerMXBean.isValid()

    private static var isValid_MethodID_6: jmethodID?

    open func isValid() -> Bool {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallBooleanMethod( object: javaObject, methodName: "isValid", methodSig: "()Z", methodCache: &MemoryManagerMXBeanForward.isValid_MethodID_6, args: &__args, locals: &__locals )
        return __return != jboolean(JNI_FALSE)
    }


    /// In declared protocol but not defined.. ///

    /// public abstract javax.management.ObjectName java.lang.management.PlatformManagedObject.getObjectName()

    // Skipping method: false false true false false 

}

