
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// interface java.lang.management.PlatformManagedObject ///

public protocol PlatformManagedObject: JavaProtocol {

    /// public abstract javax.management.ObjectName java.lang.management.PlatformManagedObject.getObjectName()

    // Skipping method: false false true false false 

}


open class PlatformManagedObjectForward: JNIObjectForward, PlatformManagedObject {

    private static var PlatformManagedObjectJNIClass: jclass?

    /// public abstract javax.management.ObjectName java.lang.management.PlatformManagedObject.getObjectName()

    // Skipping method: false false true false false 

}

