
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// class java.lang.annotation.RetentionPolicy ///

public enum RetentionPolicy: Int, JNIObjectProtocol, JNIObjectInit {

    case SOURCE, CLASS, RUNTIME

    static let enumConstants = JavaClass(loading: "java.lang.annotation.RetentionPolicy")
        .getEnumConstants()!.map { RetentionPolicyForward( javaObject: $0.javaObject ) }

    public func underlier() -> RetentionPolicyForward {
        return RetentionPolicy.enumConstants[self.rawValue]
    }

    public func localJavaObject(_ locals: UnsafeMutablePointer<[jobject]>) -> jobject? {
        return underlier().localJavaObject( locals )
    }

    public init( javaObject: jobject? ) {
        self = RetentionPolicy( rawValue: JavaEnum( javaObject: javaObject ).ordinal() )!
    }

    /// public static java.lang.annotation.RetentionPolicy java.lang.annotation.RetentionPolicy.valueOf(java.lang.String)

    private static var valueOf_MethodID_1: jmethodID?

    public static func valueOf( name: String? ) -> RetentionPolicy! {
        return RetentionPolicyForward.valueOf( name: name )
    }
    public static func valueOf( _ _name: String? ) -> RetentionPolicy! {
        return valueOf( name: _name )
    }

    /// public static java.lang.annotation.RetentionPolicy[] java.lang.annotation.RetentionPolicy.values()

    private static var values_MethodID_2: jmethodID?

    public static func values() -> [RetentionPolicy]! {
        return RetentionPolicyForward.values( )
    }

}


open class RetentionPolicyForward: JNIObjectForward {

    private static var RetentionPolicyJNIClass: jclass?

    /// private static final java.lang.annotation.RetentionPolicy[] java.lang.annotation.RetentionPolicy.$VALUES

    /// public static final java.lang.annotation.RetentionPolicy java.lang.annotation.RetentionPolicy.CLASS

    private static var CLASS_FieldID: jfieldID?

    public static var CLASS: RetentionPolicy! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "CLASS", fieldType: "Ljava/lang/annotation/RetentionPolicy;", fieldCache: &CLASS_FieldID, className: "java/lang/annotation/RetentionPolicy", classCache: &RetentionPolicyJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? RetentionPolicy( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.annotation.RetentionPolicy java.lang.annotation.RetentionPolicy.RUNTIME

    private static var RUNTIME_FieldID: jfieldID?

    public static var RUNTIME: RetentionPolicy! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "RUNTIME", fieldType: "Ljava/lang/annotation/RetentionPolicy;", fieldCache: &RUNTIME_FieldID, className: "java/lang/annotation/RetentionPolicy", classCache: &RetentionPolicyJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? RetentionPolicy( javaObject: __value ) : nil
        }
    }

    /// public static final java.lang.annotation.RetentionPolicy java.lang.annotation.RetentionPolicy.SOURCE

    private static var SOURCE_FieldID: jfieldID?

    public static var SOURCE: RetentionPolicy! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "SOURCE", fieldType: "Ljava/lang/annotation/RetentionPolicy;", fieldCache: &SOURCE_FieldID, className: "java/lang/annotation/RetentionPolicy", classCache: &RetentionPolicyJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? RetentionPolicy( javaObject: __value ) : nil
        }
    }

    /// public static java.lang.annotation.RetentionPolicy java.lang.annotation.RetentionPolicy.valueOf(java.lang.String)

    private static var valueOf_MethodID_3: jmethodID?

    open class func valueOf( name: String? ) -> RetentionPolicy! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: name, locals: &__locals )
        let __return = JNIMethod.CallStaticObjectMethod( className: "java/lang/annotation/RetentionPolicy", classCache: &RetentionPolicyJNIClass, methodName: "valueOf", methodSig: "(Ljava/lang/String;)Ljava/lang/annotation/RetentionPolicy;", methodCache: &valueOf_MethodID_3, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? RetentionPolicy( javaObject: __return ) : nil
    }

    open class func valueOf( _ _name: String? ) -> RetentionPolicy! {
        return valueOf( name: _name )
    }

    /// public static java.lang.Enum java.lang.Enum.valueOf(java.lang.Class,java.lang.String)

    private static var valueOf_MethodID_4: jmethodID?

    open class func valueOf( enumType: java_swift.JavaClass?, name: String? ) -> java_swift.JavaEnum! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 2 )
        __args[0] = JNIType.toJava( value: enumType, locals: &__locals )
        __args[1] = JNIType.toJava( value: name, locals: &__locals )
        let __return = JNIMethod.CallStaticObjectMethod( className: "java/lang/annotation/RetentionPolicy", classCache: &RetentionPolicyJNIClass, methodName: "valueOf", methodSig: "(Ljava/lang/Class;Ljava/lang/String;)Ljava/lang/Enum;", methodCache: &valueOf_MethodID_4, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? java_swift.JavaEnum( javaObject: __return ) : nil
    }

    open class func valueOf( _ _enumType: java_swift.JavaClass?, _ _name: String? ) -> java_swift.JavaEnum! {
        return valueOf( enumType: _enumType, name: _name )
    }

    /// public static java.lang.annotation.RetentionPolicy[] java.lang.annotation.RetentionPolicy.values()

    private static var values_MethodID_5: jmethodID?

    open class func values() -> [RetentionPolicy]! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallStaticObjectMethod( className: "java/lang/annotation/RetentionPolicy", classCache: &RetentionPolicyJNIClass, methodName: "values", methodSig: "()[Ljava/lang/annotation/RetentionPolicy;", methodCache: &values_MethodID_5, args: &__args, locals: &__locals )
        return JNIType.toSwift( type: [RetentionPolicy].self, from: __return )
    }


    /// public final int java.lang.Enum.compareTo(java.lang.Enum)

    // Skipping method: false true false false false 

    /// public int java.lang.Enum.compareTo(java.lang.Object)

    // Skipping method: false true false false false 

    /// public final boolean java.lang.Enum.equals(java.lang.Object)

    // Skipping method: false true false false false 

    /// public final native java.lang.Class java.lang.Object.getClass()

    // Skipping method: false true false false false 

    /// public final java.lang.Class java.lang.Enum.getDeclaringClass()

    // Skipping method: false true false false false 

    /// public final int java.lang.Enum.hashCode()

    // Skipping method: false true false false false 

    /// public final java.lang.String java.lang.Enum.name()

    // Skipping method: false true false false false 

    /// public final native void java.lang.Object.notify()

    // Skipping method: false true false false false 

    /// public final native void java.lang.Object.notifyAll()

    // Skipping method: false true false false false 

    /// public final int java.lang.Enum.ordinal()

    // Skipping method: false true false false false 

    /// public java.lang.String java.lang.Enum.toString()

    // Skipping method: false true false false false 

    /// public final native void java.lang.Object.wait(long) throws java.lang.InterruptedException

    // Skipping method: false true false false false 

    /// public final void java.lang.Object.wait(long,int) throws java.lang.InterruptedException

    // Skipping method: false true false false false 

    /// public final void java.lang.Object.wait() throws java.lang.InterruptedException

    // Skipping method: false true false false false 

}

