--- #YAML:1.0
name:                Readonly-XS
version:             1.05
abstract:            ~
license:             ~
author:              
    - Eric Roode <roode@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Readonly:                      1.02
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
