---
abstract: 'Track changes between documents'
author:
  - 'David E. Wheeler <david@justatheory.com>'
build_requires:
  File::Spec: 0
  Module::Build: 0.2701
  Test::More: 0.17
configure_requires:
  Module::Build: 0.2701
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-WordDiff
provides:
  Text::WordDiff:
    file: lib/Text/WordDiff.pm
    version: 0.08
  Text::WordDiff::ANSIColor:
    file: lib/Text/WordDiff/ANSIColor.pm
    version: 0.08
  Text::WordDiff::Base:
    file: lib/Text/WordDiff.pm
    version: 0
  Text::WordDiff::HTML:
    file: lib/Text/WordDiff/HTML.pm
    version: 0.08
  Text::WordDiff::HTMLTwoLines:
    file: lib/Text/WordDiff/HTMLTwoLines.pm
    version: 0.08
recommends:
  Test::Pod: 1.41
requires:
  Algorithm::Diff: 1.19
  HTML::Entities: 0
  Term::ANSIColor: 0
resources:
  bugtracker: http://github.com/theory/test-xpath/issues/
  homepage: http://search.cpan.org/dist/Text-WordDiff/
  license: http://dev.perl.org/licenses/
  repository: http://github.com/theory/test-xpath/tree/
version: 0.08
