# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

os: osx
osx_image: xcode10.2
language: swift
script:
- set -o pipefail && xcodebuild -project netfox.xcodeproj -scheme netfox_ios -sdk iphonesimulator12.2 ONLY_ACTIVE_ARCH=NO SWIFT_VERSION=4.2 | xcpretty
- set -o pipefail && xcodebuild -project netfox.xcodeproj -scheme netfox_ios -sdk iphonesimulator12.2 ONLY_ACTIVE_ARCH=NO SWIFT_VERSION=5.0 | xcpretty
- set -o pipefail && xcodebuild -project netfox.xcodeproj -scheme netfox_osx -sdk macosx10.14 ONLY_ACTIVE_ARCH=NO SWIFT_VERSION=4.2 | xcpretty
- set -o pipefail && xcodebuild -project netfox.xcodeproj -scheme netfox_osx -sdk macosx10.14 ONLY_ACTIVE_ARCH=NO SWIFT_VERSION=5.0 | xcpretty
- pod lib lint --quick
