name: Test

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run tests
    runs-on: macOS-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install Certificates
      uses: apple-actions/import-codesign-certs@v1
      with: 
        p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
        p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
    - name: Test
      run: xcodebuild -project CameraController.xcodeproj -scheme CameraController -sdk macosx test