url: https://swift.org
title: Swift.org
description: "Swift is a general-purpose programming language built using a modern approach to safety, performance, and software design patterns."
timezone: America/Lower_Princes
exclude: ["README.md", "config.ru", "Gemfile", "Gemfile.lock", "Procfile", "vendor"]
safe: true
future: true

kramdown:
    syntax_highlighter: rouge

sass:
    style: compressed
    sass_dir: "assets/stylesheets"

defaults:
    -
        scope:
            type: "posts"
        values:
            permalink: /blog/:title/
            layout: "post"

gems:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from
