# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         PlRPC
version:      0.2018
version_from: lib/RPC/PlServer.pm
installdirs:  site
requires:
    Net::Daemon:                   0.13
    Storable:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
