name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-macos:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    # reads .swift-version
    - uses: YOCKOW/Action-setup-swift@v1.1.14
    - run:  | 
        swift run            unit-test 
        swift run -c release integration-test --compact
        swift run -c release compression-test 
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: YOCKOW/Action-setup-swift@v1.1.14
    - run:  | 
        swift run            unit-test 
        swift run -c release integration-test --compact
        swift run -c release compression-test 
