version: "3"

services:

  runtime-setup:
    image: swift-cluster-membership:18.04-5.2
    build:
      args:
        ubuntu_version: "bionic"
        swift_version: "5.2"

  unit-tests:
    image: swift-cluster-membership:18.04-5.2

  unit-tests-until-failure:
    image: swift-cluster-membership:18.04-5.2

  integration-tests:
    image: swift-cluster-membership:18.04-5.2

  test:
    image: swift-cluster-membership:18.04-5.2

  bench:
    image: swift-cluster-membership:18.04-5.2

  shell:
    image: swift-cluster-membership:18.04-5.2
