use_frameworks!
target "My app" do
    source 'https://github.com/CocoaPods/Specs.git'
    platform :ios, '13.0'
    pod 'Alamofire', '~> 5.2'
end
install! 'cocoapods', :integrate_targets => false
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '5.2'
    end
  end
end
