---
abstract: 'Nearly transparent SSL encapsulation for IO::Socket::INET.'
author:
  - 'Steffen Ullrich & Peter Behroozi & Marko Asplund'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IO-Socket-SSL
no_index:
  directory:
    - t
    - inc
requires:
  Net::SSLeay: 1.21
  Scalar::Util: 0
version: 1.76
