--- #YAML:1.0
name:                IO-KQueue
version:             0.34
abstract:            perl interface to the BSD kqueue system call
license:             ~
author:              
    - Matt Sergeant <matt@sergeant.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
