opt_in_rules:
  - anyobject_protocol
  - closure_spacing
  - contains_over_first_not_nil
  - convenience_type
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_name
  - first_where
  - force_unwrapping
  - implicit_return
  - let_var_whitespace
  - literal_expression_end_indentation
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - private_action
  - private_outlet
  - prohibited_super_call
  - single_test_class
  - sorted_imports
  - toggle_bool
  - unused_import
  - unused_private_declaration

included:

force_cast: warning

identifier_name:
  min_length: 2

line_length: 160

disabled_rules:
  - nesting
  - custom_rules
