name: Check PR labels

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the `main` branch
on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened, labeled, unlabeled ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-labels:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    steps:
    - name: Match PR Label
      uses: zwaldowski/match-label-action@v2
      with:
        allowed_multiple: >
          API design,
          bug,
          continuous integration,
          dependencies,
          documentation,
          enhancement,
          refactor,
          SwiftUI compatibility,
          test suite,
          GTK renderer,
