desc "Builds the test"
lane :build do |options|
  recreate_schemes(
    project: options[:project]
  )
  xcodebuild(
    project: options[:project],
    scheme: "My app",
    configuration: "debug",
    clean: true,
    build: true,
    destination: "generic/platform=iOS",
    build_settings: {
      "CODE_SIGNING_REQUIRED" => "NO",
      "CODE_SIGN_IDENTITY" => "",
      "CODE_SIGNING_ALLOWED" => "NO"
    }
  )
end
