--- #YAML:1.0
name:               Data-Dump
version:            1.21
abstract:           Pretty printing of data structures
author:
    - Gisle Aas <gisle@activestate.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test:  0
requires:
    perl:    5.006
    Symbol:  0
resources:
    repository:  http://github.com/gisle/data-dump
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
recommends:
    MIME::Base64:  0
