---
abstract: "Make sure you didn't emit any warnings while testing"
author:
  - 'Fergal Daly <fergal@esatclear.ie>'
build_requires:
  Test::More: 0.47
  Test::Tester: 0.107
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112621'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-NoWarnings
no_index:
  directory:
    - t
    - inc
requires:
  Test::Builder: 0.86
  perl: 5.006
resources:
  repository: http://svn.ali.as/cpan/trunk/Test-NoWarnings
version: 1.04
