# docker-compose -f deployment/local/docker-compose.yml up

version: '3'

services:

  runtime-setup:
    image: swift-package-registry-compat-test-suite
    build:
      context: .
      dockerfile: Dockerfile

  postgres:
    image: "postgres:13.3"
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=package_registry
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    
  api:
    depends_on: [runtime-setup, postgres]
    image: swift-package-registry-compat-test-suite
    volumes:
      - ~/.ssh:/root/.ssh
      - ../..:/code:z
    working_dir: /code
    links:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=package_registry
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "9229:9229"
    command: /bin/bash -cl "API_SERVER_HOST=0.0.0.0 API_SERVER_PORT=9229 swift run PackageRegistryExample"
