name: Remove disabled formulae

on:
  push:
    paths:
    - .github/workflows/remove-disabled-formulae.yml
  schedule:
    # Once every day at midnight UTC
    - cron: "0 0 * * *"

jobs:
  remove-disabled-formulae:
    if: startsWith(github.repository, 'Homebrew/')
    runs-on: ubuntu-latest
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Configure Git user
        uses: Homebrew/actions/git-user-config@master
        with:
          username: BrewTestBot

      - name: Remove disabled formulae
        id: remove_disabled
        uses: Homebrew/actions/remove-disabled-formulae@master

      - name: Create pull request
        if: ${{ steps.remove_disabled.outputs.formulae-removed == 'true' }}
        uses: peter-evans/create-pull-request@45c510e1f68ba052e3cd911f661a799cfb9ba3a3
        with:
          token: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
          branch: remove-disabled-formulae
          title: Remove disabled formulae
          body: >
            This pull request was created automatically by the
            [`remove-disabled-formulae`](https://github.com/Homebrew/homebrew-core/blob/HEAD/.github/workflows/remove-disabled-formulae.yml)
            workflow.
