---
abstract: 'JSON::XS compatible pure-Perl module.'
author:
  - 'Makamaka Hannyaharamitu, E<lt>makamaka[at]cpan.orgE<gt>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.130880'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: JSON-PP
no_index:
  directory:
    - t
    - inc
requires:
  Test::More: 0
resources:
  repository: http://github.com/makamaka/JSON-PP
version: 2.27203
