name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    # reads .swift-version
    - uses: YOCKOW/Action-setup-swift@v1.1.14
    - run: | 
        brew install imagemagick
        utils/tests
        utils/examples -c release

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: YOCKOW/Action-setup-swift@v1.1.14
    - run: | 
        utils/tests
        utils/examples -c release
