language: generic

matrix:
  include:
    # Swift 3.1 macOS
    - os: osx
      osx_image: xcode8.3
      env:
        - BUILD_LABEL: Swift 3.1 on macOS
        - SWIFT_VERSION: system
      script:
        swift test
    # Swift 3.0 macOS
    - os: osx
      osx_image: xcode8.3
      env:
        - BUILD_LABEL: Swift 3.0 on macOS
        - SWIFT_VERSION: 3.0.2
      script:
        swift test
    # Swift 3.2/4.0 macOS
    - os: osx
      osx_image: xcode9
      env:
        - BUILD_LABEL: Swift 3.2/4.0 on macOS
        - SWIFT_VERSION: system
      script:
        swift test
    # Swift 3.0 Linux
    - os: linux
      dist: trusty
      env:
        - BUILD_LABEL: Swift 3.0 on Linux
        - SWIFT_VERSION: 3.0.2
      script:
        swift test
    # Swift 3.1 Linux
    - os: linux
      dist: trusty
      env:
        - BUILD_LABEL: Swift 3.1 on Linux
        - SWIFT_VERSION: 3.1.1
      script:
        swift test
    # Swift 3.2/4.0 Linux
    - os: linux
      dist: trusty
      env:
        - BUILD_LABEL: Swift 3.2/4.0 on Linux
        - SWIFT_VERSION: 4.0-DEVELOPMENT-SNAPSHOT-2017-07-20-a
      script:
        swift test
    # Swift 3.1 iOS 64-bit
    - os: osx
      osx_image: xcode8.3
      env:
        - BUILD_LABEL: Swift 3.1 on 64-bit iOS
        - SWIFT_VERSION: system
      script:
        xcodebuild -project Cheetah.xcodeproj -scheme Cheetah -destination 'platform=iOS Simulator,name=iPhone 7,OS=latest' test
    # Swift 3.2/4.0 iOS 64-bit
    - os: osx
      osx_image: xcode9
      env:
        - BUILD_LABEL: Swift 3.2/4.0 on 64-bit iOS
        - SWIFT_VERSION: system
      script:
        xcodebuild -project Cheetah.xcodeproj -scheme Cheetah -destination 'platform=iOS Simulator,name=iPhone 7,OS=latest' test

install:
  - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
  - swift package generate-xcodeproj
