---
abstract: 'A pure Perl HTTP proxy'
author:
  - "Philippe \"BooK\" Bruhat <book@cpan.org>"
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTTP-Proxy
provides:
  HTTP::Proxy:
    file: lib/HTTP/Proxy.pm
    version: 0.25
  HTTP::Proxy::BodyFilter:
    file: lib/HTTP/Proxy/BodyFilter.pm
  HTTP::Proxy::BodyFilter::complete:
    file: lib/HTTP/Proxy/BodyFilter/complete.pm
  HTTP::Proxy::BodyFilter::htmlparser:
    file: lib/HTTP/Proxy/BodyFilter/htmlparser.pm
  HTTP::Proxy::BodyFilter::htmltext:
    file: lib/HTTP/Proxy/BodyFilter/htmltext.pm
  HTTP::Proxy::BodyFilter::lines:
    file: lib/HTTP/Proxy/BodyFilter/lines.pm
  HTTP::Proxy::BodyFilter::save:
    file: lib/HTTP/Proxy/BodyFilter/save.pm
  HTTP::Proxy::BodyFilter::simple:
    file: lib/HTTP/Proxy/BodyFilter/simple.pm
  HTTP::Proxy::BodyFilter::tags:
    file: lib/HTTP/Proxy/BodyFilter/tags.pm
  HTTP::Proxy::Engine:
    file: lib/HTTP/Proxy/Engine.pm
  HTTP::Proxy::Engine::Legacy:
    file: lib/HTTP/Proxy/Engine/Legacy.pm
  HTTP::Proxy::Engine::NoFork:
    file: lib/HTTP/Proxy/Engine/NoFork.pm
  HTTP::Proxy::Engine::ScoreBoard:
    file: lib/HTTP/Proxy/Engine/ScoreBoard.pm
  HTTP::Proxy::Engine::Threaded:
    file: lib/HTTP/Proxy/Engine/Threaded.pm
  HTTP::Proxy::FilterStack:
    file: lib/HTTP/Proxy/FilterStack.pm
  HTTP::Proxy::HeaderFilter:
    file: lib/HTTP/Proxy/HeaderFilter.pm
  HTTP::Proxy::HeaderFilter::simple:
    file: lib/HTTP/Proxy/HeaderFilter/simple.pm
  HTTP::Proxy::HeaderFilter::standard:
    file: lib/HTTP/Proxy/HeaderFilter/standard.pm
requires:
  HTTP::Daemon: 1.25
  LWP::UserAgent: 2
  Test::More: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.25
