---
name: Time-HiRes-Value
version: 0.07
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
abstract: |-
  a class representing a time value or interval in exact
  microseconds
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Time::HiRes: 0
build_requires:
  Test::Exception: 0
  Test::More: 0
provides:
  Time::HiRes::Value:
    file: lib/Time/HiRes/Value.pm
    version: 0.07
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
