# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBIx-ContextualFetch
version:      1.03
version_from: lib/DBIx/ContextualFetch.pm
installdirs:  site
requires:
    DBI:                           1.35
    Test::More:                    0.11

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
