version: '3.0'

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    networks: [observability]
    depends_on: [jaeger]
    command: ["--config=/etc/config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/config.yaml
    ports:
      - 4317:4317

  jaeger:
    image: jaegertracing/all-in-one:latest
    networks: [observability]
    ports:
      - 16686:16686

networks:
  observability:
