# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-Std-Utils
version:      v0.0.3
version_from: lib/Class/Std/Utils.pm
installdirs:  site
requires:
    List::Util:                    0
    Scalar::Util:                  0
    Test::More:                    0
    version:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
