--- #YAML:1.0
name:                mod_perl
version:             1.30
abstract:            Embed a Perl interpreter in the Apache HTTP server
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Doug MacEachern <dougm@pobox.com>
