---
version: 2.2.0
configurations:
  debug:
    overrides:
      IPHONEOS_DEPLOYMENT_TARGET: '13.0'
  release:
    overrides:
      IPHONEOS_DEPLOYMENT_TARGET: '13.0'
targets:
  MyApp:
    sources: App
    platform: ios
    type: ":application"
    references:
    - target: FrameworkExample
      copy: true
      codeSignOnCopy: true
    configuration:
      INFOPLIST_FILE: App/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: uk.lyptt.App
      IPHONEOS_DEPLOYMENT_TARGET: '13.0'
  FrameworkExample:
    sources: FrameworkExample
    platform: ios
    type: ":framework"
    configuration:
      INFOPLIST_FILE: FrameworkExample/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: uk.lyptt.FrameworkExample
      IPHONEOS_DEPLOYMENT_TARGET: '13.0'
  FrameworkExampleTests:
    sources: FrameworkExampleTests
    references:
    - FrameworkExample
    platform: ios
    type: ":bundle.unit-test"
    configuration:
      INFOPLIST_FILE: FrameworkExampleTests/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: uk.lyptt.FrameworkExampleTests
      IPHONEOS_DEPLOYMENT_TARGET: '13.0'
      FRAMEWORK_SEARCH_PATHS:
      - $(inherited)
      - $(BUILT_PRODUCTS_DIR)