# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode11.5
language: swift
# cache: cocoapods
# podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod repo update
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild -workspace Example/Unrealm.xcworkspace -scheme Unrealm-Example  -destination "OS=13.5,name=iPhone 11 Pro Max" -configuration Release -UseModernBuildSystem=NO ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES clean test | xcpretty
